name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set execute permissions on deploy.sh
        run: chmod +x ./deploy.sh

      - name: Run deploy.sh
        run: ./deploy.sh
